# Generated by Django 2.2 on 2019-04-18 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import seeds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('phone_number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('full_name', models.CharField(max_length=70)),
                ('region', models.CharField(choices=[(seeds.models.RegionChoice('Kayes'), 'Kayes'), (seeds.models.RegionChoice('Koulikoro'), 'Koulikoro'), (seeds.models.RegionChoice('Bamako'), 'Bamako'), (seeds.models.RegionChoice('Sikasso'), 'Sikasso'), (seeds.models.RegionChoice('Ségou'), 'Ségou'), (seeds.models.RegionChoice('Mopti'), 'Mopti'), (seeds.models.RegionChoice('Tombouctou'), 'Tombouctou'), (seeds.models.RegionChoice('Gao'), 'Gao'), (seeds.models.RegionChoice('Kidal'), 'Kidal')], max_length=10)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeds.Farmer')),
            ],
            options={
                'unique_together': {('farmer_id', 'pub_date')},
            },
        ),
    ]
