# Generated by Django 2.2 on 2019-04-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_auto_20190418_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='farmer_id',
            new_name='farmer',
        ),
    ]
