# Generated by Django 2.2 on 2019-04-18 21:05

from django.db import migrations, models
import seeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_auto_20190418_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='region',
            field=models.CharField(choices=[(seeds.models.RegionChoice('Kayes'), 'Kayes'), (seeds.models.RegionChoice('Koulikoro'), 'Koulikoro'), (seeds.models.RegionChoice('Bamako'), 'Bamako'), (seeds.models.RegionChoice('Sikasso'), 'Sikasso'), (seeds.models.RegionChoice('Ségou'), 'Ségou'), (seeds.models.RegionChoice('Mopti'), 'Mopti'), (seeds.models.RegionChoice('Tombouctou'), 'Tombouctou'), (seeds.models.RegionChoice('Gao'), 'Gao'), (seeds.models.RegionChoice('Kidal'), 'Kidal')], max_length=10),
        ),
    ]
