# Generated by Django 2.2 on 2019-04-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0006_auto_20190418_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
