# Generated by Django 2.2 on 2019-04-18 23:23

from django.db import migrations, models
import seeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0007_auto_20190419_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='region',
            field=models.CharField(choices=[(seeds.models.RegionChoice('Kayes'), 'RegionChoice.REGION1'), (seeds.models.RegionChoice('Koulikoro'), 'RegionChoice.REGION2'), (seeds.models.RegionChoice('Bamako'), 'RegionChoice.REGION3'), (seeds.models.RegionChoice('Sikasso'), 'RegionChoice.REGION4'), (seeds.models.RegionChoice('Ségou'), 'RegionChoice.REGION5'), (seeds.models.RegionChoice('Mopti'), 'RegionChoice.REGION6'), (seeds.models.RegionChoice('Tombouctou'), 'RegionChoice.REGION7'), (seeds.models.RegionChoice('Gao'), 'RegionChoice.REGION8'), (seeds.models.RegionChoice('Kidal'), 'RegionChoice.REGION9')], max_length=10),
        ),
    ]
